version: 2.1

orbs:
  node: circleci/node@5.0.3
  android: circleci/android@2.1.2
  rn: react-native-community/react-native@7.1.1

commands:
  detox_build_ios:
    steps:
      - restore_cache:
          keys: 
            - ios-build-cache-{{ checksum "package.json" }}-{{ arch }}
      - run: |
          npm install -g detox-cli react-native-cli
          detox build --configuration ios.sim.debug
      - save_cache:
          key: ios-build-cache-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - ios/build/Build

  detox_build_android:
    steps:
      - android/restore-gradle-cache
      - run: |
          npm install -g detox-cli react-native-cli
          detox build --configuration android.emu.debug
      - android/save-gradle-cache

  metro_start:
    steps:
      - run:
          name: Metro (background)
          command: npm run start
          background: true

jobs:
  build:
    docker:
      - image: cimg/node:12.16
    working_directory: ~/native-circleci-detox-trial
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  build_ios:
    executor:
      name: rn/macos
      xcode_version: 14.1.0
    working_directory: ~/native-circleci-detox-trial
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - rn/setup_macos_executor
      - rn/pod_install
      - rn/ios_simulator_start:
          device: iPhone 14
      - detox_build_ios
      - save_cache:
          paths: 
            - ~/.npm
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: /native-circleci-detox-trial
          paths:
            - ios
  detox_ios:
    executor:
      name: rn/macos
      xcode_version: 14.1.0
    steps:
      - attach_workspace:
          at: /native-circleci-detox-trial/ios
      - metro_start
      - run: npm run test-ios -- --tags @passing
      - store_artifacts:
          path: artifacts

  build_android:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    working_directory: ~/native-circleci-detox-trial
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - rn/android_emulator_start:
          device_name: Pixel_5_API_30
      - detox_build_android
      - save_cache:
          paths: 
            - ~/.npm
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: pwd
      - persist_to_workspace:
          root: /native-circleci-detox-trial
          paths:
            - android

  detox_android:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - attach_workspace:
          at: /native-circleci-detox-trial/android
      - metro_start
      - run: npm run test-android -- --tags @passing
      - store_artifacts:
          path: artifacts
      
  failing_detox_android:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - attach_workspace:
          at: /native-circleci-detox-trial/android
      - run: npm run test-android -- --tags @failing
      - store_artifacts:
          path: artifacts  

workflows:
  MyTrial:
    jobs:
      - build
      - build_ios:
          requires: 
            - build
      - build_android:
          requires: 
            - build
      - detox_ios:
          requires: 
            - build_ios
      - detox_android:
          requires: 
            - build_android
      - failing_detox_android: 
          requires: 
            - build_android