version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  node:
    working_directory: ~/natice-circleci-detox-trial
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - node/install-packages
      - run: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: build detox tests
          command:
            npm run build-android
      - run:
          name: detox tests
          command:
            npm run circle-test

      - persist_to_workspace:
          root: ~/
          paths:
            - native-circleci-detox-trial
            - node_modules
            - e2e

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
  android-build-and-test:
      working_directory: ~/native-circleci-detox-trial/android
      docker:
      - image: circleci/android:api-29-node
      steps:
      - checkout:
          path: ~/native-circleci-detox-trial

      - attach_workspace:
          at: ~/native-circleci-detox-trial

      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run: bundle install

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
            
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

     
workflows:
  example-workflow:
      jobs:
        - node
        - android-build-and-test:
            requires: 
              - node

            