version: 2.1

orbs:
  node: circleci/node@5.0.3
  android: circleci/android@2.1.2
  rn: react-native-community/react-native@7.1.1
  ruby: circleci/ruby@2.0.0

commands:
  detox_build_ios:
    steps:
      - restore_cache:
          keys: 
            - ios-build-cache-{{ arch }}-{{ checksum "~/.tmp/checksumfiles/package.json" }}
      - run: |
          npm install -g detox-cli react-native-cli
          detox build --configuration ios.sum.debug
      - save_cache:
          key: ios-build-cache-{{ arch }}-{{ checksum "~/.tmp/checksumfiles/package.json" }}
          paths:
            - ios/build/Build

  detox_build_android:
    steps:
      - android/restore-gradle-cache
      - run: |
          npm install -g detox-cli react-native-cli
          detox build --configuration android.emu.debug
      - android/save-gradle-cache

jobs:
  detox_ios:
    executor:
      name: rn/macos
      xcode_version: 12.5.1
    steps:
      - checkout
      - rn/setup_macos_executor
      - run: npm install
      - rn/pod_install
      - rn/ios_simulator_start:
          device: iPhone 12
      - detox_build_ios
      - run: detox test --configuration ios --take-screenshots all
      - store_artifacts:
          path: artifacts

  detox_android:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - run: npm install
      - rn/android_emulator_start:
          device_name: Pixel_5_API_30
      - detox_build_android
      - run: detox test --configuration android.emu.debug --take-screenshots all
      - store_artifacts:
          path: artifacts

  beta_android:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - node/install-yarn
      - rn/yarn_install
      - ruby/install-deps:
          app-dir: android
      - ruby/install-deps:
          app-dir: android
      - android/restore-gradle-cache
      - run:
          command: bundle exec fastlane beta
          working_directory: android
      - android/save-gradle-cache

workflows:
  test_and_distribute:
    jobs:
      - node/test:
          app-dir: native-circleci-detox-trial 
          name: unit-test
          pkg-manager: npm
          version: 16.00.0
      - node/run:
          name: eslint
          yarn-run: lint
          pkg-manager: npm
          version: 12.22.5
      - detox_ios
      - detox_android
      - rn/android_build:
          checkout: true