version: 2.1

orbs:
  android: circleci/android@2.1.2

commands:
  metro_start:
    steps:
      - run:
          name: Metro (background)
          command: npm run start
          background: true

  detox_build_ios:
    steps:
      - metro_start
      - run: 
          name: Install detox cli
          command: npm install -g detox-cli react-native-cli
      - run:
          name: Build detox config
          command: npm run build-ios

  detox_build_android:
    steps:
      - android/restore-gradle-cache
      - metro_start
      - run: 
          name: Install detox cli
          command: npm install -g detox-cli react-native-cli
      - run:
          name: Build detox config
          command: npm run build-android
      - android/save-gradle-cache


jobs:
  node:
    working_directory: ~/native-circleci-detox-trial
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: linter
          command: |
            npm run lint

      - persist_to_workspace:
          root: ~/native-circleci-detox-trial
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

  macos-build-and-test:
    working_directory: ~/native-circleci-detox-trial
    macos:
      xcode: 11.3.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test

    steps:
      - checkout

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run: 
          command: pod install
          working_directory: ios

      - detox_build_ios

      - run: 
          name: Detox Tests
          command: npm run test-ios

      - store_artifacts:
          path: artifacts

            
  android-build-and-test:
    working_directory: ~/native-circleci-detox-trial/android
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout:
          path: ~/native-circleci-detox-trial

      - attach_workspace:
          at: ~/native-circleci-detox-trial

      - detox_build_android

      - android/start-emulator-and-run-tests:
          avd-name: Pixel_5_API_30 
          test-command: npm run test-android

      - run:
          name: Detox Tests
          command: npm run test-ios

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

workflows:
  node-android-ios:
    jobs:
      - node
      - android-build-and-test:
          requires:
            - node
      - macos-build-and-test:
          requires:
            - node
            