version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  node:
    working_directory: ~/native-circleci-detox-trial
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: detox tests
          command: |
            npm run build-android
            npm run circle-test
            java -version
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/native-circleci-detox-trial
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

workflows:
  example-workflow:
      jobs:
        - node
        

            