version: '2.1'
orbs:
  android: circleci/android@2.1.2
  rn: react-native-community/react-native@5.6.0

commands:
  detox_build_android:
    steps:
      - android/restore-gradle-cache
      - run: |
          npm install -g detox-cli react-native-cli
          detox build --configuration android.emu.debug
      - android/save-gradle-cache
jobs:
  detox_android:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - run: npm install
      - rn/android_emulator_start:
           device_name: Pixel_5_API_30
      - detox_build_android
      - run: npm run circle-test
      - store_artifacts:
           path: artifacts
  example:
    docker:
      - image: circleci/android:api-30-node
    steps:
      - android/start-emulator-and-run-tests:
          delay-adb: false 
          disable-animations: true 
          install-system-image: true 
          kill-emulators: true 
          no-audio: true 
          no-boot-anim: true 
          no-snapshot: true 
          no-window: true 
          restore-gradle-cache-post-emulator-launch: true 
          run-logcat: false 
          save-gradle-cache: true 
          verbose: true 
          wait-for-emulator: true 
          avd-name: Pixel_5_API_30 
          test-command: npm run circle-test 
          post-emulator-launch-assemble-command: npm run build-android
workflows:
  test:
    jobs:
      - detox_android
      - android/run-ui-tests:
            avd-name: Pixel_5_API_30 
            checkout: true 
            delay-adb: false 
            disable-animations: true 
            executor: 
              name: android/android-machine 
              resource-class: large
              tag: 2021.10.1
            install-system-image: true 
            kill-emulators: true 
            no-audio: true 
            no-boot-anim: true 
            no-window: true 
            post-emulator-launch-assemble-command: 
              npm install -g detox-cli react-native-cli &&
              detox build --configuration android.emu.debug
            test-command: npm run circle-test 
            verbose: true 
            wait-for-emulator: true
      - example