version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  node:
    working_directory: ~/natice-circleci-detox-trial
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - node/install-packages
      - run: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: detox tests
          command:
            circle-test

      - persist_to_workspace:
          root: ~/native-circleci-trial
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
     
workflows:
  example-workflow:
      jobs:
        - node

            