version: '2.1'
orbs:
  android: circleci/android@2.1.2
  rn: react-native-community/react-native@5.6.0

commands:
  detox_build_android:
    steps:
      - android/restore-gradle-cache
      - run: |
          
          detox build --configuration android.emu.debug
      - android/save-gradle-cache
jobs:
  detox_android:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - run: npm install
      - rn/android_emulator_start:
           device_name: Pixel_5_API_30
      - detox_build_android
      - run: npm run circle-test
      - store_artifacts:
           path: artifacts
workflows:
  test:
    jobs:
      - detox_android
      - android/run-ui-tests:
            avd-name: Pixel_5_API_30 
            checkout: true 
            delay-adb: false 
            disable-animations: true 
            executor: 
              name: android/android-machine 
              resource-class: large
              tag: 2021.10.1
            install-system-image: true 
            kill-emulators: true 
            no-audio: true 
            no-boot-anim: true 
            no-window: true 
            post-emulator-launch-assemble-command: npm run build-android 
            test-command: npm run circle-test 
            verbose: true 
            wait-for-emulator: true 