version: 2.1

orbs:
  node: circleci/node@5.0.3
  android: circleci/android@2.1.2
  rn: react-native-community/react-native@7.1.1
  ruby: circleci/ruby@2.0.0

commands:
  detox_build_ios:
    steps:
      - restore_cache:
          keys: 
            - ios-build-cache-{{ arch }}-{{ checksum "~/.tmp/checksumfiles/package.json" }}
      - run: |
          npm install -g detox-cli react-native-cli
          detox build --configuration ios.sim.debug
          npm run ios
      - save_cache:
          key: ios-build-cache-{{ arch }}-{{ checksum "~/.tmp/checksumfiles/package.json" }}
          paths:
            - ios/build/Build

  detox_build_android:
    steps:
      - android/restore-gradle-cache
      - run: |
          npm install -g detox-cli react-native-cli
          detox build --configuration android.emu.debug
      - android/save-gradle-cache

jobs:
  build:
    docker: 
      - image: cimg/node:12.16
    steps:
      - checkout
      - run: npm install
      - run: 
          name: Metro (background)
          command: npm run start
          background: true
          
  detox_ios:
    executor:
      name: rn/macos
      xcode_version: 14.1.0
    steps:
      - rn/setup_macos_executor
      - run: brew install applesimutils
      - rn/pod_install
      - rn/ios_simulator_start:
          device: iPhone 12
      - detox_build_ios
      - run: detox test --configuration ios.sim.debug --take-screenshots all
      - store_artifacts:
          path: artifacts

  detox_android:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - rn/android_emulator_start:
          device_name: Pixel_5_API_30
      - detox_build_android
      - run: detox test --configuration android.emu.debug --cleanup --take-screenshots all
      - store_artifacts:
          path: artifacts
      
workflows:
  test_and_distribute:
    jobs:
      - build
      - node/test:
          name: unit-test
          pkg-manager: npm
          run-command: test 
          version: 16.14.0
      - node/run:
          name: eslint
          npm-run: lint
          pkg-manager: npm
          version: 12.22.5
      - detox_ios:
          requires: 
            - build
      - detox_android:
          requires: 
            - build